### ISSUE TITLE
Book cardlari rasmlarida razmer ko'rsatilmagan 

### ISSUE THREAD

**Issue by shohruxsaidov** [karimovnurullo/vue-project#5]
R
<img width="1253" alt="image" src="https://github.com/karimovnurullo/vue-project/assets/115876282/b71fed0d-e495-4ea2-b639-a918690111cb">

Hozirgi holati:
rasmar cho'zilib qolgan 

Kutilgan holat:
rasm aspecti o'z holatida saqlanishi. kk (yoniga yoki bo'yiga cho'zilib ketmasligi kk )

**Comment by karimovnurullo** [comment]
Fixed
