### ISSUE TITLE
Search va pagination birga ishlatiganda xatolik

### ISSUE THREAD

**Issue by shohruxsaidov** [karimovnurullo/vue-project#7]
<img width="1501" alt="image" src="https://github.com/karimovnurullo/vue-project/assets/115876282/ed1b5331-6fa0-4eee-9c38-d62efcd8993f">

Hozirgi holati:
Sahifaga kirib biror kitob qidirilganda va pagination ishlatilganda qidirilgan tekst bog'liq bo'lmagan kitoblar chiqyapti

Kutilgan holat:
pagination qidirilgan kitobga bog'liq ishlashi kerak

Case:
- login qilinadi
- search input ga 'pets' teksti kiritiladi
- pagination da next knopkasi bosiladi

**Comment by karimovnurullo** [comment]
Fixed
